### ISSUE TITLE
Remove untar.go from code base

### ISSUE THREAD

**Issue by ZyanKLee** [noisetorch/NoiseTorch#281]
Currently the untar.go file is in the repo. We should decide on how to handle that file going forward.

One idea is to use the CLI tool `untar` or `tar`. Another to use the go file from upstream.

**Comment by TheDukeofErl** [comment]
Are we able to use the go file from upstream without copying it in ourselves due to it being an internal package? The current comment in the code as to why this was done like that seems to indicate that it can't be done.

Using GNU tar via the CLI would likely work, though that would introduce an external dependency that we can't guarantee. That said, I cannot fathom a normal installation of any modern distro that would ship without it (even Arch ships it in the base install), considering it's a relatively basic and essential part of GNU. An error message may suffice in this case. 

Given the simplicity of the file, we could accept the vendored code here, or make a noisetorch repo that has the file in it and bring it in with via go.mod. The last option here may be the best option in this case.

**Comment by ZyanKLee** [comment]
not removing it could be a valid decision here, too.

**Comment by ZyanKLee** [comment]
I'm not sure if creating a new repository just for this one file is really worth the effort.
In an effort to see how others solved this issue, I had a look around and most of the solutions were very similar approaches (code-wise).
My suggestion: Let's just keep it, it's now our job to take care of that.

**Comment by TheDukeofErl** [comment]
Yeah, I'm inclined to agree with that sentiment. If a need to change how we're doing this now presents itself in the future we can always revisit it :)

**Comment by Technetium1** [comment]
Just don't lock it...
