### ISSUE TITLE
change the name

### ISSUE THREAD

**Issue by lawl** [noisetorch/NoiseTorch#328]
The license file states

    Conveying modified versions of this program ("NoiseTorch") must be marked as modified in a reasonable way.
    Modified versions may not be conveyed to others under same name as the original program.
    Package names, source code, user interfaces and other visible appearances of the program name should make it obvious for users
    and potential users that the modified version differs from the original version of NoiseTorch it is based upon.

i believe this should now be considered a fork. as a copyright owner of some of the original code, i'm asking you to please change the name of this project to not violate the license.

**Comment by TeknosQuet** [comment]
no

**Comment by principis** [comment]
There is an argument that it's still the original program, at least if you as the copyright holder want it to be. It would be a shame if the name had to change.

**Comment by ZyanKLee** [comment]
Hello @lawl,

I disagree with your reasoning.
The way I see it, this is very much the original project and not a fork:

You created the organization and moved the original project into it. Then you invited me to the org, made me owner and left the project and community, essentially gifting it to the NoiseTorch community in its entirety.

But let's put that aside for a moment as I would like to clear some things up first:
I'm wondering what your intentions behind contesting the projects name really are? Do you still want to continue with the project in some way?

**Comment by lawl** [comment]
> Besides, that's a very annoying clause to have... It makes it impossible for packagers to apply distro-specific patches.

Good. You got the point of the clause.

> You created the organization and moved the original project into it.

https://github.com/lawl/noisetorch

is the original URL of the project and still under my control.

> I'm wondering what your intentions behind contesting the projects name really are? Do you still want to continue with the project in some way?

I'm not ruling out noisetorch-next. I disagree strongly with how it is currently being run, but i'm still not interested in maintaining the current version. As long as some people want to maintain it, that's fine. Find a new name please.

Aside from lawyering over what is the original, let me reframe the issue. Usually something like that is solved via trademarks. Trademarks are expensive and not something you just register for a hobby project. The point of this clause was to get a trademark lite via copyright (originally because some distributions are a pain in the ass). I gave my maintainer status away, not my trademark lite. You can agree with this and lawyer over what is the original project, but what you're actually doing is saying that any open source project that can't afford a trademark registration should have their project name copied by anyone.

**Comment by AXDOOMER** [comment]
@lawl did you get written permission from previous contributors before adding this clause? If not, this clause might be void. A project's license can't be changed unilaterally regardless of the size of the modifications made by other contributors. The license might have to be reverted to its original state, thus making it open source friendly again. 

Also, I counted that you wrote about 330 lines of code since adding this clause to the license and leaving the project (new code being mostly CLI code), so I believe that even if the new clause wasn't void, this project could be easily restored to the original unmodified license. 

I'd also add that given that you've moved the original project to an organization and promoted someone else as the maintainer before leaving the organization makes this project very much the original project. You've nuked the project files at your URL and everything such as the watchers, forks and stars didn't remain on your repo, indicating that your repo does not contain the original project. 

Given these facts, this repository is currently in compliance with the license and no changes are required to be made. You don't own any trademarks to the name and this does not mean that open source projects should have their name copied by anyone.

**Comment by lawl** [comment]
> Also, I counted that you wrote about 330 lines of code since adding this clause to the license

clean room them then

**Comment by TheDukeofErl** [comment]
> You've nuked the project files at your URL

It actually even goes beyond this. After lawl/NoiseTorch was transferred to noisetorch/NoiseTorch, lawl/NoiseTorch would redirect to noisetorch/NoiseTorch. lawl/NoiseTorch, as it stands now, was created on May 26. This can easily be seen via the initial commit, https://github.com/lawl/NoiseTorch/commit/77e951f789219fb4d2ada896958f9305df0ee046. 

> @lawl did you get written permission from previous contributors before adding this clause?

I'd like to ask the same question: lawl, did you receive written consent from the previous contributors prior to adding the section 7(c) clause? There may be an inherent misunderstanding here: one party cannot unilaterally change a GPLv3 license without receiving this consent from all other, previous contributors. Alternatively, did all contributors explicitly waive all rights to their code and sign the rights to their code over to you? Though possible, I highly doubt that this was occurring due to the legal costs of getting a framework like this set up.

**Comment by lawl** [comment]
@TheDukeofErl i dont think you understand how licenses work. i can most certainly license my newer code under a different license as long as its compatible with the GPL. since the added clause is explicitly allowed, it most certainly does not restrict your 4 freedoms or whatever and is compatible with the GPL. as i said above, clean room the changes, or change the name. or just let it die.

**Comment by AXDOOMER** [comment]
It doesn't work that way. You're relicensing the entire program and not only your new code. You need to get consent from other contributors.

**Comment by principis** [comment]
Ok, let's remove the code added after the license change, revert the license, and keep the name.

**Comment by RiemaruKarurosu** [comment]
> I'm not ruling out noisetorch-next. I disagree strongly with how it is currently being run, but i'm still not interested in maintaining the current version.

I don't understand what you don't like, the last version only has not much modified, only the necessary to work and it's only the audit.

And the things that I think you don't like, like flatpak, the vendor. Are open discussions.

**Comment by TheDukeofErl** [comment]
> I think the argument is about the title, not about the content. The title is not the content of the code. The title was there before the license.

At this point to me, the question becomes if we can remove the section 7(c) clause if we change the name. If we can remove that clause with a name change (which will likely require reaching out to the FSF to determine if that can be done) then it's a much more reasonable course of action. To my understanding, changing the name will simply leave us in the same position: we're unable to let downstream make any distro-specific changes for packaging and are open to future legal issues. 

For me at least, that's the most important part going forward. It's the same reason I'm concerned over the unilateral change of the license and whatever legal implications that may have. To this end, I believe that it's once again going to require reaching out to the FSF legal team as to the intricacies of both the original license change and any implications of if the change was not in compliance with the requirements of changing a GPL license.

What I'm saying is that even if this argument is over the name of the program, there's going to be some legal issues here no matter what. I'd really rather not have this become a legal issue but I can't see any situation in which, at the very least, the FSF legal team isn't contacted over this license question.

**Comment by AXDOOMER** [comment]
> I would **_much_** prefer to be forced to change the name. Nuking code for the sake of it, or cleanrooming it otherwise is a waste of both the time and effort we've put in already. Lawl wants the NoiseTorch name to die, so let's let it die in favor of something else.

I might be repeating a few things Kevin said, but changing the name of the project is only one of the requirements from the amendment to the license. It also states that the user interface and visible appearance must be changed, so changing the name doesn't solve the code rewrite issue. We have the right to keep the name because this is the original NoiseTorch project. All we need is to get rid of the amendment to the license so that the project is pure GPL3 and can be distributed with patches from distro maintainers. 

A legal opinion from a FSF lawyer will help us sort that out, but if Lawl's point of contention is the name, then @lawl , would you agree that we can remove the whole section (addition terms to Section 7, subsection `c`) that you've stated [here](https://github.com/noisetorch/NoiseTorch/issues/328#issue-1265441621) if we were to rename the project even if we didn't comply with `Package names, source code, user interfaces and other visible appearances of the program name should make it obvious for users and potential users that the modified version differs from the original version of NoiseTorch it is based upon.`?

**Comment by lawl** [comment]
@Technetium1 

> ...

I don't care

> Is there a timeframe legally bound to this I'm some way? (i.e. will a legal issue be brought if it's not solved within the next month?)

If I say no you I'm telling you it's fine to never do it. If I say yes ill sue you in a month, that would obviously be ridiculous.

I don't have anything more to add to this thread. Won't be answering questions.

**Comment by luni3359** [comment]
Why are you doing this?

**Comment by Technetium1** [comment]
RE @lawl:
> figure it out

Doing my best to help in a timely manner.

> If I say no you I'm telling you it's fine to never do it. If I say yes ill sue you in a month, that would obviously be ridiculous.

I see the point you're making there. Thank you for replying.

**Comment by lawl** [comment]
Since it seems you guys are here to stay I think a general timeline would be pretty helpful. Like what to expect in the coming days/weeks.

**Comment by Technetium1** [comment]
I'm ***not*** an official contributor, but I'm still actively asking around to see if there are ideas for new names on different platforms, as you can tell by my edit times on the discussion I opened.

**Comment by lawl** [comment]
Quick reminder that the 30 days are over.

**Comment by Technetium1** [comment]
As I can only speak for myself as a non-official contributor - I have no idea what 'the plan' is at this moment. Things continue to progress in the new name discussion. I appreciate your patience while things are gotten into order though.

**Comment by AXDOOMER** [comment]
Hi @lawl !

I am pleased to inform you that the project is being renamed, albeit this may be temporary as we are planning a clean room rewrite of some parts of the project using the Chinese wall approach so we can get rid of the extra term to the license. 

For the rename, see https://github.com/noisetorch/NoiseTorch/pull/348.

**Comment by ZyanKLee** [comment]
Thanks @AXDOOMER and @TheDukeofErl for preparing the name change on short notice.

@lawl please review the changes and report back if you agree with our assessment that these are in line with your additional license terms.

**Comment by Technetium1** [comment]
@ZyanKLee please check your Gmail for some useful context for this situation.

**Comment by ryleu** [comment]
Not to add fuel to the fire (apologies for the mild necropost), but what is your reasoning @lawl ? I understand that you don't want to maintain the project, but why work to undermine the efforts of a community that loved what you made enough to preserve it?

Why not just grant permission to consider the clause you added as void and then move on?

I want to understand the reasoning so I can be more sympathetic, because right now, you're coming off as a jerk who wants to be destructive for the sake of it.

If that's all it is, fine, but I don't believe that's the case.

**Comment by 10maurycy10** [comment]
@lawl 

You cant just relicence code contributed by others, you need the permission of *all* the contributers, even as the origonal creator.

Because the GPL requires derivatives to be under the same licence, even the ~300 lines you added after the insertion of the clause, is not effected.

In fact, this is *the* point of the GPL: to prevent restrictions being placed on software by anyone, including the original creator.

**Comment by DrMcCoy** [comment]
> Not to add fuel to the fire (apologies for the mild necropost), but what is your reasoning @lawl ?

I have mostly no horse in this race (*), but that's @lawl's business alone, and I think they made it pretty clear that they don't want to further elaborate on this. Further prodding serves no point, nor does calling them a jerk. My voice carries no weight, but I'd suggest just moving on.

(*) I don't even use noisetorch at the moment, I use cadmus. Since that's unmaintained, it seems, I'm keeping an eye out on alternatives like noisetorch in the case cadmus breaks for me.

> You cant just relicence code contributed by others, you need the permission of all the contributers, even as the origonal creator.

That's true. From a legal standpoint, relicensing the code doesn't work that way, as far as I am aware (IANAL, etc.). There's precedence for this: VLC relicensed their code from GPLv2 (with the "or later" clause) to LGPLv2.1 (again with the "or later" clause); this was a major undertaking that took them several years. You can find write-ups with a quick googling.

Again IANAL, but from what I understand, the name is a bit of a special case, because that's not necessarily copyright law, but trademark law, and the GPL doesn't offer any widespread permissions there. The GPLv3 even has a clause that explictly allows adding trademark _restrictions_ (while many types of other restrictions to GPL'd code are void).

The details on how that applies to whether @lawl can outright demand a name change depends on the jurisdiction, because trademark law is less unified than copyright law. Personally, I think just changing the damn name is kinder thing to do. No need to antagonize people further, and really, what's in a name, especially for a comparably smaller project like this.

**Comment by ZyanKLee** [comment]
IMHO this topic had been discussed and all viable options have been presented.

We decided on a path to move forward (which was to change the name of the program until we will have removed the code that had been relicensed), whatever parks lawl's intentions and feeling are, we asked about them and never got an answer (which is ok).

I feel like the discussion is also developing in a direction that is neither helpful nor do I approved of the tone and wording of some of the latest comments.

I'll close this topic now. Let's focus on the present and future instead, please.
