### ISSUE TITLE
Slower fade in to prevent pops/clicks when activating

### ISSUE THREAD

**Issue by duckbytes** [noisetorch/NoiseTorch#346]
**Is your feature request related to a problem? Please describe.**
When starting to say something, there is a noticeable pop/click at the start of the word. It sounds like the voice activation is going straight from silent to full without any fade in.

**Describe the solution you'd like**
A fast fade in when voice is activated.

**Describe alternatives you've considered**
A noise gate added to the chain with a longer attack length helps to suppress the click a little.

**Additional context**

https://user-images.githubusercontent.com/32309223/176511320-285e3c31-447f-4ba5-913e-0d60f7c26a6d.mp4

Sound sample. The click is most noticeable on the second word.

Recorded using noisetorch 0.12.2 with pipewire.

**Comment by TheDukeofErl** [comment]
Have you tried adjusting the Voice Activation Threshold at all to try to deal with this? I think that lowering it may help a bit.

We could otherwise look at adjusting the grace period in https://github.com/noisetorch/NoiseTorch/blob/master/c/ladspa/module.c, which I'm sure would also have some form of an impact here as well.

**Comment by duckbytes** [comment]
Lowering the threshold does seem to help, thanks. I still get occasional clicks but less than before. It didn't occur to me that adjusting that slider could help with this.
