### ISSUE TITLE
Noisetorch microphone sometimes just stops working completely. (Pipewire)

### ISSUE THREAD

**Issue by psychoo167** [noisetorch/NoiseTorch#349]
I used to use Noisetorch before and it worked fine. Recently it's started to work weirldy, it just wouldn't work at all for some reason and I need to reload it every 15 minutes or so, and sometimes it makes my voice all robotic. 
My linux distro is Pop!_OS (Latest version).
Any help?

**Comment by zwessels** [comment]
same here

are there any logs that we can provide to help debug the issue?

**Comment by TheDukeofErl** [comment]
Are there any steps to reproduce? It'd be helpful if someone could go through and fill out the new bug information. I haven't had any issues like that and I'm wondering what's different in the steps that are causing it. @zwessels, I assume you're on Pop as well?

**Comment by ZyanKLee** [comment]
Thanks a lot for providing that information.
I used NT yesterday for 3 hours straight with pipewire on a Ubuntu 22.04. So apparently I could not reproduce it.

Not saying it does not happen at yours, but I'm leaning on searching the fault outside of NT.

**Comment by zwessels** [comment]
complete shot in the dark, but are the `alsa` references correct in `pactl list short`?

e.g.

```
536870913	module-ladspa-source	source_name='NoiseTorch Microphone for RØDE NT-USB Mini' master=alsa_input.usb-R__DE_Microphones_R__DE_NT-USB_Mini_F70298F1-00.mono-fallback rate=48000 channels=1 label=noisetorch plugin=/tmp/librnnoise-50840104.so control=75	
54	alsa_output.usb-FiiO_DigiHug_USB_Audio-01.analog-stereo	PipeWire	s24le 2ch 48000Hz	RUNNING
54	alsa_output.usb-FiiO_DigiHug_USB_Audio-01.analog-stereo.monitor	PipeWire	s24le 2ch 48000Hz	RUNNING
55	alsa_input.usb-FiiO_DigiHug_USB_Audio-01.analog-stereo	PipeWire	s24le 2ch 48000Hz	RUNNING
56	alsa_input.usb-R__DE_Microphones_R__DE_NT-USB_Mini_F70298F1-00.mono-fallback	PipeWire	s24le 1ch 48000Hz	RUNNING
```

**Comment by ginop-1** [comment]
similar problem here

**Describe the bug**
NoiseTorch microphone doesn't capture anything

**To Reproduce**
Happens automatically

**Desktop (please complete the following information):**
- Distribution: arch linux (5.18.14)
- DE: KDE 
- Pulseaudio version: 16.
- NoiseTorch-ng Version: 0.12.2

I'm not using pipewire

**Logs**
pactl list: https://pastebin.com/5PFJhWPh
noisetorch logs: https://pastebin.com/LqbSCs0S

**Comment by TheDukeofErl** [comment]
This is kind of a shot in the dark but is it possible that this is due to USB device suspension? An example set of steps:

1. Plug monitor into PC (USB)
2. Plug mic into monitor (USB)
3. Start NoiseTorch-ng
4. Allow monitor to go to sleep (suspending USB from the monitor)
5. Wake the computer/monitor
6. Observe that NoiseTorch-ng has stopped working

An alternative set of steps may be:

1. Plug mic into PC (USB)
2. Start NoiseTorch-ng
3. Allow system to suspend (go to sleep)
4. Wake the computer
5. Observe that NoiseTorch-ng has stopped working

To my knowledge, there is some degree of an issue related to that specific case. I don't see anything like this in the logs, but at the same time, I don't believe that there would be much indicated in the logs for that anyways. It may also kind of match the "mystery issue" case. Even so, if that is the issue, I don't have much of a solution past not having the system sleep.

For what it's worth, I'm also using Arch and KDE, but am using pipewire. That said, the issue I'm describing should be distro, de, and pipewire/pulseaudio agnostic. 

> complete shot in the dark, but are the `alsa` references correct in `pactl list short`?

Nothing there jumps out at me as looking wrong.

> similar problem here

Looking at the pactl list, the only thing that seems a little finicky here is that bitrates are being mixed. I believe this has caused me issues in the past with Pipewire but might not with Pulseaudio.

**Comment by zwessels** [comment]
so i think i may found something

i am using a usb fiio dac with my headphones. i noticed that when i ran `dmesg` i would see output like this:

```
[193250.781495] retire_capture_urb: 2492 callbacks suppressed
[193255.783527] retire_capture_urb: 2491 callbacks suppressed
[193260.787588] retire_capture_urb: 2492 callbacks suppressed
[193265.789579] retire_capture_urb: 2491 callbacks suppressed
[193270.793639] retire_capture_urb: 2492 callbacks suppressed
[193275.797636] retire_capture_urb: 2492 callbacks suppressed
[193280.799666] retire_capture_urb: 2491 callbacks suppressed
...
```

others have reported that this is due to the sample rate not set [1].

in any event, i decided to disconnect the dac completely and just directly plug my headphones into the motherboard.

after that, i restarted noise torch and i haven't had any issues with noise torch since then. 

i will monitor the progress and report back if it stops working again.

[1] https://www.reddit.com/r/kernel/comments/9fr915/comment/ebt8jmu/

**Comment by TheDukeofErl** [comment]
> ...i decided to disconnect the dac completely and just plug my headphones directly into the motherboard...

This makes a lot of sense to me: I had a similar issue at one point with a FiiO e17 and Blue Yeti mic. This prior to starting to use NoiseTorch. The sample rate on the mic, the monitor on the mic, and the FiiO didn't seem to want to line up no matter what. My solution was very similar to what you did: I use S/PDIF off my motherboard to the FiiO DAC and plug the Yeti in via USB.

**Comment by red-star-fighter** [comment]
I have the same issue using a blue yeti via usb. The issue happens most of the time for me while alt tabbing to a game using proton; it seems to be a newer issue as this had not affected me before the security screening this project went through.

**Comment by ginop-1** [comment]
> similar problem here
> 
> **Describe the bug** NoiseTorch microphone doesn't capture anything after being started
> 
> **To Reproduce** Happens automatically
> 
> **Desktop (please complete the following information):**
> 
>     * Distribution: arch linux (5.18.14)
> 
>     * DE: KDE
> 
>     * Pulseaudio version: 16.1
> 
>     * NoiseTorch-ng Version: 0.12.2
> 
> 
> I'm not using pipewire
> 
> **Logs** pactl list: https://pastebin.com/5PFJhWPh noisetorch logs: https://pastebin.com/LqbSCs0S

UPDATE: switching to PipeWire seems to solve the issue, idk why

**Comment by psychoo167** [comment]
Oh god, I forgot to close this issue cause the issue solved itself for me, I had to just re-install my OS. Sorry.
