### ISSUE TITLE
Security Issue Seems to be still ongoing - This app broke my OS

### ISSUE THREAD

**Issue by Ruok2bu** [noisetorch/NoiseTorch#398]
**Describe the bug**
After installing the latest version my computer broke. Applications in Linux Mint stopped starting, other applications crashed. Seems the security incident is still ongoing as the application is still infected with malware. To anyone who sees this. Avoid this application at all costs! I had to format and reinstall my computer because even system apps stopped working!

**To Reproduce**
1. Install application.
2. Swear at computer when things break or act very virusey.

**Expected behavior**
The application should be free of malware but due to what happened, i wont ever be trying it again.

**Screenshots**

**Logs**
If applicable, add the link to a pastebin with the output of `noisetorch -log` and `pactl list short`.

**Desktop (please complete the following information):**
 - Linux Mint. 21.1
 - Pulseaudio/Pipewire Version: 
 - NoiseTorch-ng Version [e.g. v0.12.12]:

**Additional context**

**Comment by TheDukeofErl** [comment]
Sorry to hear you had an odd issue with your system. I'd highly recommend checking your disk's integrity using a tool like `smartctl`. I'd probably be looking to, at a minimum, use that to run a long test as well as trying to check your system's memory for any issues. Many Linux ISOs should include memtest. I don't know if the Mint ISO does or doesn't, though. You should probably do a memory test prior to running a SMART test for what it's worth, as failing memory may impact other things.

I'd also like to clear up a misconception: the software codebase never had any issues with malware to begin with. The problem was due to a relatively questionable method of serving updates, in which it was served from a server that the previous developer ran, rather than using Github's built in tools, as well as that developer's keys being compromised, leading to an audit. To reiterate the results of the community-driven code inspection, we have no reason to believe that there are any issues with malware or the like in NT. The results of the audit that was performed can be seen here: https://github.com/noisetorch/NoiseTorch/discussions/275.

**Comment by Ruok2bu** [comment]
I did run a full system scan to rule out hardware failure. I ran memtest86+ for 24 hours to check for memory errors (none were found), did a stress test of the cpu for a few hours (no crashes occurred), did a stress test of the hard drive and scanned for errors too. The computer is pristine condition.

**Comment by AXDOOMER** [comment]
Nothing indicates that the issue you had is directly related to NoiseTorch. If it was infected by malware, it wouldn't show up as clean when scanned with anti-viruses and I would expect it to break my computer like it did to yours, but it doesn't.

**Comment by Technetium1** [comment]
As someone who has very painstakingly been watching every commit for months since personally auditing the codebase, you most assuredly did not get malware from the application distributed here.

If you'd like a second opinion on your disk health, post the complete SMART stats here. You can use `smartctl` with Linux or `CrystalDiskInfo` with Windows.
