### ISSUE TITLE
[FEATURE REQUEST] Force LADSPA plugin to stay on Null output instead of switching to default sink.

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [noisetorch/NoiseTorch#79]
Oops. hit enter to early.

Basically, if i have my headphones as the default output, and then switch that to my speakers, it switches the LADSPA plugin to suppress my speakers instead of the Null Output, so it in turn breaks the noise suppression. I wanted to ask if it was possible for you to force the plugin to use the Null Output no matter what, so I wouldn't have to reload pulseaudio every time i want to switch to and from my headphones.

**Comment by ShaunTheQuietGamer** [comment]
What is the state of this? Do you think it is even possible? I really want to use this program but it is really annoying having to reload the plugin every time I switch from my speakers to my headphones, as it kills pulseaudio sometimes, causing a whole bunch of issues with other programs.

**Comment by lawl** [comment]
possible: i don't know.

state: i'm currently not working on it.

**Comment by Alfagun74** [comment]
I also have this problem and i would love to see a solution!

**Comment by reitzig** [comment]
I have had similar issues when recording Zoom sessions; not sure if it's related. I suddenly heard myself via my headphones and the recording was silent.

**Comment by lawl** [comment]
I've just tested this again, and it works fine for me. This should have been fixed [here](https://github.com/lawl/NoiseTorch/commit/7dfd54e87874a648a6bce08be16b001e28fab35a).

Are you sure that your microphone is not just picking up your speakers?

**Comment by reitzig** [comment]
Yes; I was using headphones.

I haven't tried this again; in fact, I haven't been using noisetorch at all in a while since it turned out to be too unreliable (occasional robot sound, bad noise, etc) esp. when switching between Teams and Zoom, for whatever reason. I know, too unspecific for you to act on. :shrug: Still, can't keep restarting noisetorch and pulseaudio throughout the day, rejoining meetings several times. So sadly, I had to drop it for now.

**Comment by ZyanKLee** [comment]
afaict this should not be an issue anymore. Will close it, but if you still encounter issues like that, please tell us.
